### ISSUE TITLE
Output doesn't give a lot of details on what resourceType was exported

### ISSUE THREAD

**Issue by prb112** [smart-on-fhir/bulk-data-client#5]
Output doesn't give a lot of details on what resourceType was exported:

```
Downloading exported files: ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0%
          Downloaded Files: 0 of 13
            FHIR Resources: 0
               Attachments: 0
           Downloaded Size: 0.0 B
```

It'd be great if there was an indication of what ResourceType this references.

Thanks, this is a great tool.

**Comment by vlad-ignatov** [comment]
This shows the total downloaded resources count (of any kind). Otherwise it would have to be dynamic and show a separate counter for every resource type. That would mean up to about 10 - 15 additional rows (or up to 100 - 150 for servers that support everything).

There ate three types of information that a client might need:
1. The total number of downloaded resources - currently implemented
2. The resource types that you've gotten - available if you look at the download destination folder or the manifest
3. The resource count for every type - can be found in the manifest if the server supports that (and if the `saveManifest` option is set to true)

With that said, do you still think this needs updating?
